### ISSUE TITLE
Image Size and Licence

### ISSUE THREAD

**Issue by maxmunzel** [bitfragment/mindoc#3]
Hi!  Thank you for your great work, I really appreciate the minimalism
and pandoc integration!

Two things I stumbled upon:

 1. High resolution Images seem to expand to
infinity and I cant figure out, where in the pandoc template to fix this.

2. I also cant find any licence, which makes me hesitant to use it,
could you provide one?

Kind Regards

Max

**Comment by bitfragment** [comment]
Hi Max: Thanks! I will add a MIT license.

The place to handle image sizing would be in [extra.css](https://github.com/bitfragment/mindoc/blob/master/src/css/extra.css) or, if you're editing one of the HTML template files directly, in the section marked `<!-- Extra styles -->`.
